# Generated by Django 3.0.8 on 2020-07-23 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pghistory', '0002_aggregateevent'),
        ('tutorial', '0002_fsm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_field', models.IntegerField()),
                ('char_field', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TrackedEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('int_field', models.IntegerField()),
                ('char_field', models.CharField(max_length=64)),
                ('id', models.IntegerField()),
                ('pgh_context', models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.Context')),
                ('pgh_obj', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='event', to='tutorial.Tracked')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
